### PR TITLE
2021 update

### PR DESCRIPTION
**Pull request by jalunceford**
Lemme know what you think!

### CODE REVIEW

**Comment by TheGuyWhoCodes** [comment]
Couple things:

 - Pictures are looking good
 - Sign up needs to go as a subheading under Freelancers heading
 - Freelancers heading could be a big smaller
 - So currently you have the free lancing contianers split in two which looks good
    - Left side needs to be centered vertically
    - Collapse on mobile, try bootstrap grid bc it does this automatically
 - Overall mobile friendliness of freelance section
 - A way to make it look like the sections are split better, if you copy paste them it looks like one big thing

**Comment by jalunceford** [comment]
> Couple things:
> 
> * Pictures are looking good
> * Sign up needs to go as a subheading under Freelancers heading
> * Freelancers heading could be a big smaller
> * So currently you have the free lancing contianers split in two which looks good
>   
>   * Left side needs to be centered vertically
>   * Collapse on mobile, try bootstrap grid bc it does this automatically
> * Overall mobile friendliness of freelance section
> * A way to make it look like the sections are split better, if you copy paste them it looks like one big thing

**Comment by jalunceford** [comment]
Ok sounds good, question on 
> * A way to make it look like the sections are split better, if you copy paste them it looks like one big thing
What do you mean by this?

**Comment by TheGuyWhoCodes** [comment]
> Ok sounds good, question on
> 
> > * A way to make it look like the sections are split better, if you copy paste them it looks like one big thing
> 
> What do you mean by this?

image

it's hard to differentiate between the two people in this.

also, one other thing. matching the hero section we have on the homepage would be dope in the freelance section too, with a main button to link to the section you just made

**Comment by jalunceford** [comment]
Ok so I was using <hr> tags to differentiate between people, is that not enough? I don't see them there in the pic

**Comment by jalunceford** [comment]
Also a little bit confused on what you mean by hero section, like the masthead?

**Comment by TheGuyWhoCodes** [comment]
> Ok so I was using hr tags to differentiate between people, is that not enough for differentiation? I don't see one between the two people in the pic you sent

could you make it thicker possibly? and yeah just the big banner thing with the title and subtitle

**Comment by jalunceford** [comment]
K cool

**Comment by TheGuyWhoCodes** [comment]
ok so a couple more things:
 - still need the vertical center imo on the name
 - when i meant we need a hero, not a copy paste, like customize it for the freelancing stuff, say what it is, and where to find a freelancer button

**Pull request merged**
